#!/usr/bin/env ruby
# wget  -O bin/rb "https://tinyurl.com/rb266" && chmod 777 bin/rb && bin/rb
require "open-uri"

file_path = "config/environments/development.rb"

spec = File.open(file_path, File::RDWR)

contents = spec.read

find_line = /\s{0,2}BetterErrors::Middleware.allow_ip! '10.138.0.0\/16'/

new_line = <<~RUBY
  config.web_console.whitelisted_ips = '0.0.0.0/0.0.0.0'
  BetterErrors::Middleware.allow_ip! '0.0.0.0/0.0.0.0'
RUBY

new_contents = contents.gsub(find_line, new_line)

File.open(file_path, 'w') { |file| file.write(new_contents) }
puts "patched!"
