#!/usr/bin/env ruby
# wget  -O bin/fus "https://tinyurl.com/u31min" && chmod 777 bin/fus && bin/fus
require "open-uri"

file_path = "spec/features/calendar_spec.rb"

spec = File.open(file_path, File::RDWR)

contents = spec.read

find_line = "/calendar_invite/resutls"
new_line = '/calendar_invite/results'

new_contents = contents.gsub(find_line, new_line)

File.open(file_path, 'w') { |file| file.write(new_contents) }

