#!/usr/bin/env ruby
# wget  -O bin/ifx "url" && chmod 777 bin/ifx && bin/ifx
require "open-uri"
spec_path = "spec/scripts/array_count_1_spec.rb"

format_file = File.open(spec_path, File::RDWR)

text = File.open(spec_path).read
url = "https://raw.githubusercontent.com/appdev-projects/array-chapter/master/spec/scripts/array_count_1_spec.rb"
new_content = open(url).read

File.open(format_file, "w") { |file| file << new_content }

