#!/bin/bash
# # wget  -O bin/flyi "https://tinyurl.com/addflyctl" && chmod 777 bin/flyi && bin/flyi
curl -L https://fly.io/install.sh | sh
echo 'export FLYCTL_INSTALL="~/.fly"' >> ~/.bashrc
echo 'export PATH="$FLYCTL_INSTALL/bin:$PATH"' >> ~/.bashrc
source ~/.bashrc
echo "done"
