#!/usr/bin/env ruby
# wget  -O bin/psignin "url" && chmod 777 bin/psignin && bin/psignin

spec_path = "spec/features/user_auth_spec.rb"

format_file = File.open(spec_path, File::RDWR)

text = File.open(spec_path).read
url = "https://raw.githubusercontent.com/appdev-projects/photogram-signin/jw-update-specs-and-dev-prime/spec/features/user_auth_spec.rb"
new_content = open(url).read

format_file.seek(0)
format_file.write(new_content)
