#!/usr/bin/env ruby
# wget  -O bin/redup "url" && chmod 777 bin/redup && bin/redup
require "open-uri"
spec_path = "spec/features/user_auth_spec.rb"

format_file = File.open(spec_path, File::RDWR)

text = File.open(spec_path).read
url = "https://raw.githubusercontent.com/appdev-projects/photogram-signin/master/spec/features/user_auth_spec.rb"
new_content = open(url).read

File.open(format_file, "w") { |file| file << new_content }

