#!/usr/bin/env ruby
# wget  -O bin/revolve "url" && chmod 777 bin/revolve && bin/revolve
require "open-uri"
format_path = "spec/features/1_rock_spec.rb"

format_file = File.open(format_path, File::RDWR)

text = File.open(format_path).read

new_content = open("https://raw.githubusercontent.com/appdev-projects/rps-html/jw-just-for-the-hotfix/spec/features/1_rock_spec.rb").read


format_file.seek(0)
format_file.write(new_content)

url = "https://raw.githubusercontent.com/appdev-projects/rps-html/jw-just-for-the-hotfix/spec/features/2_paper_spec.rb"

format_path = "spec/features/2_paper_spec.rb"

format_file = File.open(format_path, File::RDWR)

text = File.open(format_path).read

new_content = open(url).read

format_file.seek(0)
format_file.write(new_content)

url = "https://github.com/appdev-projects/rps-html/raw/jw-just-for-the-hotfix/spec/features/3_scissors_spec.rb"

format_path = "spec/features/3_scissors_spec.rb"

format_file = File.open(format_path, File::RDWR)

text = File.open(format_path).read

new_content = open(url).read

format_file.seek(0)
format_file.write(new_content)
