#!/usr/bin/env ruby
# wget  -O bin/sub_zero "url" && chmod 777 bin/sub_zero && bin/sub_zero
require "open-uri"
`bundle u grade_runner`
format_path = "spec/support/json_output_formatter.rb"

format_file = File.open(format_path, File::RDWR)

url = "https://raw.githubusercontent.com/appdev-projects/rps-html/master/spec/support/json_output_formatter.rb"
text = File.open(format_path).read

new_content = open(url).read

format_file.seek(0)
format_file.write(new_content)

spec_file = "spec/features/puzzle_spec.rb"

text = File.open(spec_file).read
spec_puzzle_file = File.open(spec_file, File::RDWR)

new_content = text.gsub(":points => 0", ":points => 1")

spec_puzzle_file.seek(0)
spec_puzzle_file.write(new_content)
